application: sinmetalcraft
module: default
version: 20151012a
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 100

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /css
  static_dir: webapp/css
- url: /images
  static_dir: images
- url: /javascript
  static_dir: webapp/javascript
- url: /template
  static_dir: webapp/template
- url: /admin/.*
  script: _go_app
  login: admin
- url: /tq/.*
  script: _go_app
  login: admin
- url: /cron/.*
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
